services:
  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: madina
      POSTGRES_PASSWORD: m123
      POSTGRES_DB: expensedb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U madina"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: expense_tracker_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/expensedb
      SPRING_DATASOURCE_USERNAME: madina
      SPRING_DATASOURCE_PASSWORD: m123
    ports:
      - "8080:8080"

volumes:
  postgres_data:
