name: Java CI with Maven, Docker, and SonarCloud in Linux
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11 ]
        include:
             - java: 8
               maven-args: "-DrepoToken=$COVERALLS_REPO_TOKEN coveralls:report"
             - java: 11
               maven-args: "-DrepoToken=$COVERALLS_REPO_TOKEN coveralls:report"
             - java: 17
               maven-args: "sonar:sonar -Dsonar.projectKey=madinakuldeeva_personal-expense-tracker -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN"
    
    
    name: Build with Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Cache Maven and SonarCloud packages
      uses: actions/cache@v3
      with:
         path: |
            ~/.m2
            ~/.sonar/cache
         key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml') }}
         restore-keys: ${{ runner.os }}-m2-
    - name: Build with Maven
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: xvfb-run mvn clean verify -Pjacoco ${{ matrix.maven-args }}
